services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python musicdownload.py
    region: oregon  # Adjust region as needed
